### ISSUE TITLE
Remove Collider that is built with Big Car

### ISSUE THREAD

**Issue by EliCDavis** [EliCDavis/VR-Project-Organizer#19]
Right now people can accidentally grab the large display car in the scene. That shouldn't happen

**Comment by krlsmnk** [comment]
So removing the collider from the prefab would likely be a poor idea, since the mini cars need that to both stay on the table and trigger the inspection platform? 
I can very likely get this done. I assume the script on the inspection platform includes the call to summon the big car.
Unless we parent the car to an empty Game Object on the lift's top, it will need some sort of collider to stay on it (unless we freeze it in space and just move it a predefined amount when the lift moves, but that seems like bad practice).

What solution would you like me to go with?

**Comment by EliCDavis** [comment]
This is already completed in dev/eli/lidar-coloring-and-vehicle I just don't close tickets till their merged into master.
